services:
  mysql:
    image: mysql:8.4
    container_name: lost-found-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "68562520"
      MYSQL_DATABASE: lost_found
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./sql/data.sql:/docker-entrypoint-initdb.d/02-data.sql:ro
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p68562520"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.2
    container_name: lost-found-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "68562520"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "68562520", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
  redis_data:
